function analysis_dir = name_analysis_dir(cfg)
% create name of the folder given the GLM configuraton

if ~isempty(cfg.confounds{1})
    condounds = char(cfg.confounds{1}');
    condounds = condounds(:,1:3)';
    condounds = condounds(:)';
else
    condounds = '0';
end

analysis_dir = [ ...
    'GLM_' ...
    'ExplMask-' num2str(cfg.explicit_mask) '_' ...
    'MaskThresh-' num2str(cfg.inclusive_mask_threshold) '_' ...
    'HPF-' sprintf('%03.0f',cfg.HPF) '_' ...
    'Design-' cfg.design{1} '_' ...
    'Duration-' cfg.duration{1} '_' ...
    'RT-' num2str(cfg.RT_correction) '_', ...
    'ButtonPress-' num2str(cfg.model_button_press) '_' ...
    'UnrespTrials-' num2str(cfg.rm_unresp_trials.do) '_' ...
    'ShortRTThres-' num2str(cfg.rm_unresp_trials.thres) '_' ...
    'TimeDer-' num2str(cfg.time_der) '_' ...
    'DispDer-' num2str(cfg.disp_der) '_' ...
    'Confounds-' condounds '_' ...
    'FDCensor-' num2str(cfg.FD_censor.do) '_' ...
    'FDCensorThres-' num2str(cfg.FD_censor.thres) '_' ...
    'SpherCorr-' cfg.spher_cor{1} ...
    ];

fprintf('  %s\n', analysis_dir)

end

